In [42]:
import numpy as np
import pandas as pd

In [43]:
df = pd.DataFrame([[9,9,5],[8,10,6],[7,11,7],[7,12,8]],columns=['cgpa','score','package'])

In [44]:
df

cgpa  score  package
0     9      9        5
1     8     10        6
2     7     11        7
3     7     12        8

In [45]:
import tensorflow
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [46]:
model = Sequential()
model.add(Dense(2,activation="linear",input_dim=2))
model.add(Dense(1,activation="linear"))

/home/sai-deekshith/Documents/Machine_Learning/.venv1/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [47]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [48]:
model.get_weights()

[array([[ 0.6182169 ,  0.26494908],
        [-0.28952694, -0.9544951 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[1.2157565 ],
        [0.12140858]], dtype=float32),
 array([0.], dtype=float32)]

In [49]:
wts = [
    np.array([[0.1, 0.1],        # w1: shape (2, 2)
              [0.1, 0.1]], dtype=np.float32),

    np.array([0.0, 0.0], dtype=np.float32),  # b1: shape (2,)

    np.array([[0.1],              # w2: shape (2, 1)
              [0.1]], dtype=np.float32),

    np.array([0.0], dtype=np.float32)       # b2: shape (1,)
]

In [50]:
wts

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [51]:
from tensorflow import keras

In [52]:
model.set_weights(wts)

In [53]:
optimizer  = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [56]:
model.fit(df.iloc[:,0:-1].values,df['package'],epochs=76,verbose=1,batch_size=1)

Epoch 1/76
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.8674 
Epoch 2/76
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.5711 
Epoch 3/76
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.2638 
Epoch 4/76
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.3555 
Epoch 5/76
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.9524 
Epoch 6/76
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.6083 
Epoch 7/76
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.9087 
Epoch 8/76
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.8537 
Epoch 9/76
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.2104 
Epoch 10/76
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.6947 
Epoch 11/76
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8842 
Epoch 12/76
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.8640
Epoch 13/76
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.9457
Epoch 14/76
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.2473 
Epoch 15/76
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.5450 
Epoch 16/76
4/4 ━━━━━━━━━━━━━━━━━━

In [57]:
model.get_weights()

[array([[0.3886539 , 0.3886539 ],
        [0.41650435, 0.41650435]], dtype=float32),
 array([0.30476236, 0.30476236], dtype=float32),
 array([[0.40843534],
        [0.40843534]], dtype=float32),
 array([0.22321288], dtype=float32)]