In [135]:
import numpy as np
import pandas as pd

In [136]:
df = pd.DataFrame([[9,9,5],[8,10,6],[7,11,7],[7,12,8]],columns=['cgpa','score','package'])

In [137]:
df

cgpa  score  package
0     9      9        5
1     8     10        6
2     7     11        7
3     7     12        8

In [138]:
def init(dims):
    np.random.seed(4)
    params = {}
    l = len(dims)

    for i in range(1,l):
        params['w'+str(i)]= np.ones((dims[i-1],dims[i]))*0.1
        params['b'+str(i)] = np.zeros((dims[i],1))

    return params

In [139]:
print(init([3,2,1]))

{'w1': array([[0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1]]), 'b1': array([[0.],
       [0.]]), 'w2': array([[0.1],
       [0.1]]), 'b2': array([[0.]])}


In [140]:
def lin_forw(A_prev,w,b):
    z = np.dot(w.T,A_prev)+b
    return z
def L_layer_forward(X,params):
    A=X
    L = len(params)//2

    for l in range(1,L+1):
        A_prev = A
        w1 = params['w'+str(l)]
        b1 = params['b'+str(l)]

        print(f"A{str(l-1)} : {A_prev}")
        print(f"W{str(l)} : {w1}")
        print(f"b{str(l)} : {b1}")
        print("----"*15)

        A = lin_forw(A_prev,w1,b1)
        print(f"A{str(l)} : {A}")
        print("~~~"*30)

    return A,A_prev
    

In [141]:
X = df[['cgpa','score']].values[0].reshape(2,1)
y = df['package'].values[0]
print(X)
print(y)

[[9]
 [9]]
5


In [142]:
parameters = init([2,2,1])
print(parameters)

{'w1': array([[0.1, 0.1],
       [0.1, 0.1]]), 'b1': array([[0.],
       [0.]]), 'w2': array([[0.1],
       [0.1]]), 'b2': array([[0.]])}


In [143]:
L_layer_forward(X,parameters)

A0 : [[9]
 [9]]
W1 : [[0.1 0.1]
 [0.1 0.1]]
b1 : [[0.]
 [0.]]
------------------------------------------------------------
A1 : [[1.8]
 [1.8]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A1 : [[1.8]
 [1.8]]
W2 : [[0.1]
 [0.1]]
b2 : [[0.]]
------------------------------------------------------------
A2 : [[0.36]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


(array([[0.36]]),
 array([[1.8],
        [1.8]]))

In [144]:
#loss - (y-y_hat)^square
(y - 0.32)**2

21.902399999999997

In [145]:
parameters['w2'][1][0]

0.1

##### {'w1':
##### array([[0.1,0.1],
##### [0.1, 0.1]]),
##### ---------------
##### 'b1': array([[0.],
#####  [0.]]), 
##### --------------
##### 'w2': 
##### array([[0.1,
#####  0.1]]), 
##### --------------
#####  'b2': array([[0.]])}

In [146]:
# - x - = + (in formula of gd,That's why we add)
def upd_params(params,y,y_hat,A1,x,lr=0.001):
    params['w1'][0][0] = params['w1'][0][0] + (lr * 2 * (y-y_hat) * params['w2'][0][0]* x[0][0])
    params['w1'][0][1] = params['w1'][0][1] + (lr * 2 * (y-y_hat) * params['w2'][0][0]* x[1][0])
    params['b1'][0][0] = params['b1'][0][0] + (lr * 2 * (y-y_hat) * params['w2'][0][0])

    params['w1'][1][0] = params['w1'][1][0] + (lr * 2 * (y-y_hat) * params['w2'][1][0]* x[0][0])
    params['w1'][1][1] = params['w1'][1][1] + (lr * 2 * (y-y_hat) * params['w2'][1][0]* x[1][0])
    params['b1'][1][0] = params['b1'][1][0] + (lr * 2 * (y-y_hat) * params['w2'][1][0])

    params['w2'][0][0]= params['w2'][0][0] + (lr * 2 * (y-y_hat) * A1[0][0])
    params['w2'][1][0]= params['w2'][1][0] + (lr * 2 * (y-y_hat) * A1[1][0])
    params['b2'][0][0]= params['b2'][0][0] +(lr * 2 * (y-y_hat))
    

In [147]:
print(f"X: {X}")
print(f"y: {y}")
print(f"Parameters: {parameters}")

X: [[9]
 [9]]
y: 5
Parameters: {'w1': array([[0.1, 0.1],
       [0.1, 0.1]]), 'b1': array([[0.],
       [0.]]), 'w2': array([[0.1],
       [0.1]]), 'b2': array([[0.]])}


In [148]:
y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]
print(y_hat)
print(f"A1 is : {A1}")

A0 : [[9]
 [9]]
W1 : [[0.1 0.1]
 [0.1 0.1]]
b1 : [[0.]
 [0.]]
------------------------------------------------------------
A1 : [[1.8]
 [1.8]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A1 : [[1.8]
 [1.8]]
W2 : [[0.1]
 [0.1]]
b2 : [[0.]]
------------------------------------------------------------
A2 : [[0.36]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0.36000000000000004
A1 is : [[1.8]
 [1.8]]


In [149]:
upd_params(parameters,y,y_hat,A1,X)

In [150]:
print(f"Parameters: {parameters}")

Parameters: {'w1': array([[0.108352, 0.108352],
       [0.108352, 0.108352]]), 'b1': array([[0.000928],
       [0.000928]]), 'w2': array([[0.116704],
       [0.116704]]), 'b2': array([[0.00928]])}


In [151]:
X = df[['cgpa','score']].values[1].reshape(2,1)
y = df['package'].values[1]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]
print(y_hat)
print(f"A1 is : {A1}")

A0 : [[ 8]
 [10]]
W1 : [[0.108352 0.108352]
 [0.108352 0.108352]]
b1 : [[0.000928]
 [0.000928]]
------------------------------------------------------------
A1 : [[1.951264]
 [1.951264]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A1 : [[1.951264]
 [1.951264]]
W2 : [[0.116704]
 [0.116704]]
b2 : [[0.00928]]
------------------------------------------------------------
A2 : [[0.46472063]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0.46472062771200007
A1 is : [[1.951264]
 [1.951264]]


In [152]:
upd_params(parameters,y,y_hat,A1,X)

In [153]:
print(f"Parameters: {parameters}")

Parameters: {'w1': array([[0.11868783, 0.12127178],
       [0.11868783, 0.12127178]]), 'b1': array([[0.00221998],
       [0.00221998]]), 'w2': array([[0.13830558],
       [0.13830558]]), 'b2': array([[0.02035056]])}


In [154]:
X = df[['cgpa','score']].values[2].reshape(2,1)
y = df['package'].values[2]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]
print(y_hat)
print(f"A1 is : {A1}")
upd_params(parameters,y,y_hat,A1,X)
print(f"Parameters: {parameters}")

A0 : [[ 7]
 [11]]
W1 : [[0.11868783 0.12127178]
 [0.11868783 0.12127178]]
b1 : [[0.00221998]
 [0.00221998]]
------------------------------------------------------------
A1 : [[2.13860088]
 [2.18511211]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A1 : [[2.13860088]
 [2.18511211]]
W2 : [[0.13830558]
 [0.13830558]]
b2 : [[0.02035056]]
------------------------------------------------------------
A2 : [[0.6183442]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0.618344203004094
A1 is : [[2.13860088]
 [2.18511211]]
Parameters: {'w1': array([[0.13104449, 0.14068939],
       [0.13104449, 0.14068939]]), 'b1': array([[0.00398522],
       [0.00398522]]), 'w2': array([[0.16560121],
       [0.16619485]]), 'b2': array([[0.03311387]])}


In [155]:
X = df[['cgpa','score']].values[3].reshape(2,1)
y = df['package'].values[3]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]
print(y_hat)
print(f"A1 is : {A1}")
upd_params(parameters,y,y_hat,A1,X)
print(f"Parameters: {parameters}")

A0 : [[ 7]
 [12]]
W1 : [[0.13104449 0.14068939]
 [0.13104449 0.14068939]]
b1 : [[0.00398522]
 [0.00398522]]
------------------------------------------------------------
A1 : [[2.4938305 ]
 [2.67708371]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A1 : [[2.4938305 ]
 [2.67708371]]
W2 : [[0.16560121]
 [0.16619485]]
b2 : [[0.03311387]]
------------------------------------------------------------
A2 : [[0.89101275]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0.8910127486042558
A1 is : [[2.4938305 ]
 [2.67708371]]
Parameters: {'w1': array([[0.14752609, 0.16894356],
       [0.14758517, 0.16904484]]), 'b1': array([[0.00633973],
       [0.00634817]]), 'w2': array([[0.20105843],
       [0.20425756]]), 'b2': array([[0.04733184]])}


### The above code is for 1 epoch like that we have to do many epochs for minimum loss 

#### executing all code at one place

In [156]:
def init(dims):
    np.random.seed(4)
    params = {}
    l = len(dims)

    for i in range(1,l):
        params['w'+str(i)]= np.ones((dims[i-1],dims[i]))*0.1
        params['b'+str(i)] = np.zeros((dims[i],1))
    return params
    
def lin_forw(A_prev,w,b):
    z = np.dot(w.T,A_prev)+b
    return z
def L_layer_forward(X,params):
    A=X
    L = len(params)//2
    for l in range(1,L+1):
        A_prev = A
        w1 = params['w'+str(l)]
        b1 = params['b'+str(l)]
        A = lin_forw(A_prev,w1,b1)
    return A,A_prev    

In [157]:
params = init([2,2,1])

for i in range(15):
    loss = []
    for k in range(df.shape[0]):
        X = df[['cgpa','score']].values[k].reshape(2,1)
        y = df['package'].values[k]
        
        y_hat,A1 = L_layer_forward(X,params)
        y_hat = y_hat[0][0]
        upd_params(params,y,y_hat,A1,X)
        
        loss.append(((y-y_hat)**2))
    print(f"Epoch {i+1} loss- {np.array(loss).mean()}")

Epoch 1 loss- 35.85803704527892
Epoch 2 loss- 23.266957511558484
Epoch 3 loss- 7.928155473447658
Epoch 4 loss- 1.6029981869679724
Epoch 5 loss- 1.212481355231775
Epoch 6 loss- 1.3453243319750443
Epoch 7 loss- 1.3853174838384565
Epoch 8 loss- 1.3944020199777294
Epoch 9 loss- 1.397035284623935
Epoch 10 loss- 1.398490698499606
Epoch 11 loss- 1.399808465066595
Epoch 12 loss- 1.4011898707498134
Epoch 13 loss- 1.4026735053495045
Epoch 14 loss- 1.404266623095727
Epoch 15 loss- 1.4059704855428352


In [158]:
params

{'w1': array([[0.26367527, 0.44756494],
        [0.26732066, 0.46775164]]),
 'b1': array([[0.02717539],
        [0.02838018]]),
 'w2': array([[0.47228783],
        [0.53917713]]),
 'b2': array([[0.11753625]])}